### ISSUE TITLE
Conda环境下，运行报错。

### ISSUE THREAD

**Issue by bingshuizhang** [Henryhaohao/Wenshu_Spider#3]
(base) E:\2018CoutDocu\1HenryhaohaoWenshu_Spider\Wenshu_Spider-master\Wenshu_Pro
ject>scrapy crawl Wenshu
Traceback (most recent call last):
  File "C:\Anaconda3\Scripts\scrapy-script.py", line 10, in <module>
    sys.exit(execute())
  File "C:\Anaconda3\lib\site-packages\scrapy\cmdline.py", line 149, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "C:\Anaconda3\lib\site-packages\scrapy\crawler.py", line 252, in __init__

    log_scrapy_info(self.settings)
  File "C:\Anaconda3\lib\site-packages\scrapy\utils\log.py", line 149, in log_sc
rapy_info
    for name, version in scrapy_components_versions()
  File "C:\Anaconda3\lib\site-packages\scrapy\utils\versions.py", line 35, in sc
rapy_components_versions
    ("pyOpenSSL", _get_openssl_version()),
  File "C:\Anaconda3\lib\site-packages\scrapy\utils\versions.py", line 43, in _g
et_openssl_version
    import OpenSSL
  File "C:\Anaconda3\lib\site-packages\OpenSSL\__init__.py", line 8, in <module>

    from OpenSSL import rand, crypto, SSL
  File "C:\Anaconda3\lib\site-packages\OpenSSL\rand.py", line 12, in <module>
    from OpenSSL._util import (
  File "C:\Anaconda3\lib\site-packages\OpenSSL\_util.py", line 6, in <module>
    from cryptography.hazmat.bindings.openssl.binding import Binding
  File "C:\Anaconda3\lib\site-packages\cryptography\hazmat\bindings\openssl\bind
ing.py", line 12, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ImportError: DLL load failed: 操作系统无法运行 %1。

**Comment by Henryhaohao** [comment]
你好:
      你看下这篇博客吧, [https://blog.csdn.net/qq_31550425/article/details/78758235](url)
感谢支持!~:smile: @bingshuizhang

**Comment by bingshuizhang** [comment]
这个问题已经解决了。谢谢你，回复好快！

**Comment by Henryhaohao** [comment]
haha，没事，解决了就好。谢谢你的支持!~:heart: @bingshuizhang
